import { db } from "./db";
import { indicators } from "@shared/schema";

const seedIndicators = [
  {
    name: "Quantum Trend Pro",
    slug: "quantum-trend-pro",
    shortDescription: "Advanced trend-following algorithm with multi-timeframe confluence detection and dynamic trailing stops.",
    description: "Quantum Trend Pro is a next-generation trend-following indicator built for serious traders who demand precision. Using proprietary multi-timeframe analysis, it identifies high-probability trend continuations while filtering out market noise.\nThe algorithm combines exponential moving average crossovers with volatility-adjusted momentum filters to deliver clean, actionable signals. Unlike traditional trend indicators, Quantum Trend Pro adapts to changing market conditions in real-time, automatically adjusting sensitivity based on current volatility regimes.\nWhether you trade forex, crypto, stocks, or futures, this indicator provides clear entry and exit signals with calculated stop-loss and take-profit levels for every trade setup.",
    category: "Trend Following",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Multi-timeframe trend confluence engine",
      "Dynamic trailing stop-loss system",
      "Volatility-adjusted signal sensitivity",
      "Auto-calculated TP/SL levels",
      "Works on all markets and timeframes",
      "Real-time push notifications",
    ],
    winRate: "73.2%",
    avgReturn: "+2.8%",
    totalTrades: "1,247",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "GBP/USD", "Gold (XAU/USD)", "Crude Oil", "S&P 500", "NASDAQ"],
    bestTimeframes: ["5 min", "15 min", "1 hour", "4 hour", "Daily"],
    signalLogic: "Quantum Trend Pro uses a three-layer trend detection system. The first layer identifies the macro trend direction using a 200-period adaptive moving average. The second layer confirms momentum alignment across 3 timeframes using proprietary EMA crossovers (9/21/55). The third layer applies a volatility filter based on ATR percentile ranking to avoid signals during choppy, low-conviction markets.\nWhen all three layers align, the indicator generates a high-confidence signal marked with a colored arrow on the chart. Green arrows indicate bullish confluence, red arrows indicate bearish confluence. A strength meter (1-5 bars) shows the conviction level of each signal.",
    entryConditions: "LONG ENTRY: Green arrow appears when the 9 EMA crosses above the 21 EMA, the 55 EMA is sloping upward, price is above the 200 adaptive MA, and ATR is above the 25th percentile. Confirmation requires the signal candle to close above the 9 EMA.\nSHORT ENTRY: Red arrow appears when the 9 EMA crosses below the 21 EMA, the 55 EMA is sloping downward, price is below the 200 adaptive MA, and ATR is above the 25th percentile. Confirmation requires the signal candle to close below the 9 EMA.\nAVOID: Do not trade when the strength meter shows 1-2 bars, or when the background color turns gray (indicating a ranging/choppy market).",
    exitConditions: "EXIT LONG: When the 9 EMA crosses back below the 21 EMA, or the dynamic trailing stop is hit, or the take-profit target is reached. An early exit warning (yellow triangle) appears when momentum divergence is detected.\nEXIT SHORT: When the 9 EMA crosses back above the 21 EMA, or the dynamic trailing stop is hit, or the take-profit target is reached.\nTRAILING STOP: The dynamic trailing stop follows price using a 2x ATR distance, tightening to 1.5x ATR when the trade is in 2R profit or more.",
    stopLossStrategy: "Initial stop-loss is placed at 2x ATR from entry price. For LONG trades, stop is placed below the most recent swing low or 2x ATR below entry, whichever is tighter. For SHORT trades, stop is placed above the most recent swing high or 2x ATR above entry. The indicator auto-plots these levels on the chart as dashed red lines. Risk per trade should not exceed 1-2% of account equity.",
    targetStrategy: "Take-profit targets are calculated using a Risk-Reward framework. TP1 is set at 1.5R (1.5x the stop-loss distance), TP2 at 2.5R, and TP3 at 4R. Partial profit booking is recommended: close 40% at TP1, 30% at TP2, and trail remaining 30% with the dynamic trailing stop. All target levels are auto-plotted as green dashed lines on the chart.",
    recommendedSettings: "SCALPING (1-5 min): Fast EMA: 5, Medium EMA: 13, Slow EMA: 34, ATR Period: 10, ATR Filter: 20th percentile. Best for Nifty 50, Bank Nifty, Bitcoin.\nINTRADAY (15 min - 1 hour): Fast EMA: 9, Medium EMA: 21, Slow EMA: 55, ATR Period: 14, ATR Filter: 25th percentile. Best for all instruments. This is the default and recommended setting.\nSWING (4 hour - Daily): Fast EMA: 13, Medium EMA: 34, Slow EMA: 89, ATR Period: 20, ATR Filter: 30th percentile. Best for Forex pairs, Gold, and indices.\nPOSITIONAL (Weekly): Fast EMA: 21, Medium EMA: 55, Slow EMA: 144, ATR Period: 26, ATR Filter: 35th percentile. Best for stocks and long-term crypto holdings.",
  },
  {
    name: "Volume Profile Elite",
    slug: "volume-profile-elite",
    shortDescription: "Institutional-grade volume analysis with point of control, value area, and HVN/LVN detection.",
    description: "Volume Profile Elite reveals where institutional money is positioned by mapping volume distribution across price levels. This is the same methodology used by hedge funds and proprietary trading firms to identify key support, resistance, and fair value zones.\nThe indicator automatically plots the Point of Control (POC), Value Area High (VAH), and Value Area Low (VAL) for any selected range. It also highlights High Volume Nodes (HVN) where price is likely to consolidate and Low Volume Nodes (LVN) where price tends to move quickly.\nUse Volume Profile Elite to understand the story behind price action and make decisions based on where real money has been exchanged.",
    category: "Volume Analysis",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Automatic POC, VAH, VAL calculation",
      "High/Low Volume Node detection",
      "Session, visible range, and fixed range profiles",
      "Customizable value area percentage",
      "Delta volume integration",
      "Clean, non-cluttered visualization",
    ],
    winRate: "68.5%",
    avgReturn: "+2.1%",
    totalTrades: "982",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "Gold (XAU/USD)", "Crude Oil", "S&P 500", "NASDAQ", "Dow Jones"],
    bestTimeframes: ["15 min", "30 min", "1 hour", "4 hour", "Daily"],
    signalLogic: "Volume Profile Elite constructs a histogram of volume traded at each price level over a specified range. The Point of Control (POC) is the price with the highest traded volume — it acts as a magnet for price and strong support/resistance. The Value Area (VA) encompasses 70% of total volume and defines the fair value zone.\nHigh Volume Nodes (HVN) indicate areas of acceptance where price consolidated and large positions were built. Low Volume Nodes (LVN) are rejection zones where price moved quickly, acting as potential breakout or breakdown triggers. The indicator color-codes these zones: blue for POC, green for HVN, red for LVN.",
    entryConditions: "LONG ENTRY: Price pulls back to the POC or VAL from above with a bullish rejection candle (hammer, engulfing, or pin bar). Confirmation when price closes back above the POC with increasing volume. Also valid when price breaks above VAH with volume surge (delta positive).\nSHORT ENTRY: Price rallies to the POC or VAH from below with a bearish rejection candle. Confirmation when price closes back below the POC with increasing volume. Also valid when price breaks below VAL with volume surge (delta negative).\nBREAKOUT TRADE: When price breaks through an LVN zone with strong momentum, enter in the direction of the break targeting the next HVN.",
    exitConditions: "EXIT LONG: When price reaches the next HVN above entry, or when price breaks below the POC with a strong bearish candle and volume confirmation. Partial exits at each HVN level encountered during the trade.\nEXIT SHORT: When price reaches the next HVN below entry, or when price breaks above the POC with bullish volume. Partial exits at each HVN.\nGENERAL: Exit immediately if price fails to hold the value area edge (VAH/VAL) for more than 2 candles after entry.",
    stopLossStrategy: "For POC bounce trades: Place stop-loss 1 tick beyond the opposite side of the value area (if entering long at VAL, stop goes below the developing low). For breakout trades through LVN: Stop goes at the midpoint of the LVN zone. Maximum stop distance should not exceed 1.5x the height of the value area. The indicator marks suggested stop levels with a red dashed line.",
    targetStrategy: "Target the next HVN for conservative targets. For aggressive targets, aim for the opposite value area boundary (VAH if entered at VAL, and vice versa). When trading breakouts, target the next POC from a higher/lower timeframe. Multi-target approach: TP1 at first HVN (+40% close), TP2 at opposite VA boundary (+30% close), trail rest to next session's POC.",
    recommendedSettings: "INTRADAY (15-30 min): Profile Type: Session, Value Area %: 70%, Resolution: Fine, Show Delta: On. Best for Nifty, Bank Nifty, and index futures.\nSWING (1-4 hour): Profile Type: Weekly, Value Area %: 70%, Resolution: Medium, Show Delta: Off. Best for Forex, Crypto, and commodities.\nPOSITIONAL (Daily): Profile Type: Monthly, Value Area %: 68%, Resolution: Coarse, Show Delta: Off. Best for stocks, ETFs, and long-term analysis.\nCUSTOM RANGE: Select any date range manually to analyze specific consolidation zones. Useful for pre-earnings analysis or event-driven trading.",
  },
  {
    name: "Smart Money Tracker",
    slug: "smart-money-tracker",
    shortDescription: "Track institutional order flow with order block detection, liquidity sweeps, and fair value gap mapping.",
    description: "Smart Money Tracker is designed for traders who follow the Smart Money Concepts (SMC) methodology. It automates the detection of institutional order blocks, fair value gaps (FVG), and liquidity pools that drive market structure.\nThe indicator identifies where banks and institutions are placing their orders by analyzing market structure breaks, change of character (CHoCH) signals, and break of structure (BOS) events. It marks order blocks that have the highest probability of being revisited and highlights fair value gaps that act as magnets for price.\nCombine this with the built-in liquidity sweep detector to anticipate stop hunts and enter trades where smart money enters.",
    category: "Smart Money",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Automatic order block detection and grading",
      "Fair value gap mapping with fill tracking",
      "Liquidity pool and sweep detection",
      "Break of Structure (BOS) alerts",
      "Change of Character (CHoCH) signals",
      "Multi-timeframe structure overlay",
    ],
    winRate: "71.8%",
    avgReturn: "+3.4%",
    totalTrades: "856",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "GBP/USD", "USD/JPY", "Gold (XAU/USD)", "S&P 500", "NAS100"],
    bestTimeframes: ["1 min", "5 min", "15 min", "1 hour", "4 hour"],
    signalLogic: "Smart Money Tracker analyzes market structure in real-time by identifying swing highs and swing lows. A Break of Structure (BOS) occurs when price breaks a previous swing high (bullish) or swing low (bearish), confirming trend continuation. A Change of Character (CHoCH) occurs when the trend reversal is confirmed — a bearish CHoCH is when a previous swing low breaks in an uptrend.\nOrder blocks are the last opposing candle before a BOS — these zones mark where institutional orders were placed. The indicator grades order blocks as Strong (unmitigated, with FVG), Medium (unmitigated, no FVG), or Weak (partially mitigated). FVGs are three-candle imbalances where the middle candle's body doesn't overlap with wicks of the outer candles — these gaps act as magnets for price.",
    entryConditions: "LONG ENTRY (Premium): After a bullish BOS, wait for price to retrace into a bullish order block (OB). Enter when a bullish rejection candle forms within the OB zone, especially if an FVG aligns with the OB. Higher probability when the OB is graded 'Strong'.\nLONG ENTRY (Discount): After a bullish CHoCH, wait for price to sweep sell-side liquidity (stop hunt below recent lows), then enter when price re-enters the range with a strong bullish candle.\nSHORT ENTRY: Mirror of long entries. After bearish BOS, enter at bearish OB. After bearish CHoCH, enter after buy-side liquidity sweep.\nCONFLUENCE FILTER: Higher probability trades occur when the higher-timeframe (HTF) structure aligns with the lower-timeframe (LTF) entry.",
    exitConditions: "EXIT LONG: When price reaches the next significant swing high or untested supply zone. Also exit if a bearish CHoCH occurs on the entry timeframe, signaling potential reversal. Partial exits at intermediate liquidity pools (equal highs).\nEXIT SHORT: When price reaches the next significant swing low or untested demand zone. Exit on bullish CHoCH.\nIMPORTANT: If the order block is fully mitigated (price passes through it), the trade thesis is invalidated — exit immediately regardless of P&L.",
    stopLossStrategy: "Place stop-loss 1-2 ticks below the order block low (for longs) or above the order block high (for shorts). If trading a liquidity sweep setup, the stop goes below/above the sweep wick. Never move stop-loss further from entry — only trail in profit. The indicator marks the exact invalidation zone with a red shaded area. Recommended risk: 0.5-1% per trade due to the precision of these setups.",
    targetStrategy: "TP1: The nearest opposing order block or untested liquidity pool (equal highs/lows). Typical R:R of 1:3 to 1:5. TP2: The next BOS level from a higher timeframe. TP3: The premium/discount zone boundary (50% of the larger range). Trail remaining position using the most recent BOS level as a trailing stop. Smart Money setups often yield 1:4 to 1:10 R:R when aligned with the higher timeframe.",
    recommendedSettings: "SCALPING (1-5 min): Structure Period: 5 candles, OB Lookback: 50, FVG Sensitivity: High, Show Liquidity: On. Best for Nifty, Bank Nifty, BTC during high-volume sessions.\nINTRADAY (15 min): Structure Period: 8 candles, OB Lookback: 100, FVG Sensitivity: Medium, Show Liquidity: On. Best for Forex, indices. This is the recommended default.\nSWING (1-4 hour): Structure Period: 12 candles, OB Lookback: 200, FVG Sensitivity: Low, Show Liquidity: Off. Best for Forex, Gold, Crypto.\nHTF OVERLAY: Enable multi-timeframe mode to see Daily/Weekly structure on lower timeframe charts for confluence.",
  },
  {
    name: "Momentum Surge",
    slug: "momentum-surge",
    shortDescription: "Catch explosive moves early with RSI divergence detection, momentum oscillator, and exhaustion signals.",
    description: "Momentum Surge identifies the exact moments when momentum is building for explosive price moves. Using a proprietary blend of RSI divergence analysis, MACD histogram patterns, and volume-weighted momentum scoring, it pinpoints high-probability breakout and reversal setups.\nThe indicator features a unique \"Surge Score\" that combines multiple momentum factors into a single, easy-to-read value. When the score crosses key thresholds, it generates clear buy or sell signals with corresponding confidence levels.\nMomentum Surge also includes an exhaustion detector that warns when a trend is losing steam, helping you exit positions before reversals occur.",
    category: "Momentum",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Proprietary Surge Score algorithm",
      "Multi-factor RSI divergence detection",
      "Momentum exhaustion warnings",
      "Volume-weighted momentum analysis",
      "Breakout anticipation signals",
      "Configurable alert thresholds",
    ],
    winRate: "66.9%",
    avgReturn: "+2.5%",
    totalTrades: "1,534",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "Solana (SOL)", "EUR/USD", "Gold (XAU/USD)", "Crude Oil", "Tesla (TSLA)", "Apple (AAPL)"],
    bestTimeframes: ["5 min", "15 min", "1 hour", "4 hour", "Daily"],
    signalLogic: "The Surge Score is a composite metric (0-100) calculated from: RSI momentum (25% weight), MACD histogram slope (25% weight), volume rate of change (25% weight), and price acceleration relative to ATR (25% weight). When the Surge Score crosses above 70, it signals bullish momentum building. When it crosses below 30, bearish momentum is building.\nDivergence detection compares price swings against the Surge Score. A bullish divergence (price makes lower low, Surge Score makes higher low) signals potential reversal upward. A bearish divergence (price makes higher high, Surge Score makes lower high) signals potential reversal downward. The exhaustion detector triggers when the Surge Score reaches extreme levels (>90 or <10) and begins to fade.",
    entryConditions: "MOMENTUM LONG: Surge Score crosses above 70 with the histogram turning green and volume above the 20-period average. Enter at the close of the signal candle. Higher confidence when RSI is between 50-65 (not yet overbought).\nDIVERGENCE LONG: Bullish divergence confirmed with the Surge Score crossing back above 40 from below 30. Enter when the signal candle closes above the previous swing's high.\nMOMENTUM SHORT: Surge Score crosses below 30 with red histogram and above-average volume.\nDIVERGENCE SHORT: Bearish divergence confirmed with Surge Score crossing below 60 from above 70.\nAVOID: Do not trade when the Surge Score is between 40-60 (neutral zone). Wait for a clear directional bias.",
    exitConditions: "EXIT LONG: When the exhaustion detector triggers (Surge Score > 90 and fading), or when a bearish divergence forms, or when the Surge Score drops back below 50. Partial exits recommended when the histogram bars begin shortening.\nEXIT SHORT: When the exhaustion detector triggers (Surge Score < 10 and recovering), or when a bullish divergence forms, or when the Surge Score rises back above 50.\nEARLY EXIT: If volume drops below 50% of average during the trade, momentum may be fading — consider tightening stops.",
    stopLossStrategy: "For momentum entries: Stop-loss at 1.5x ATR below entry (longs) or above entry (shorts). For divergence entries: Stop below the divergence swing low (longs) or above the divergence swing high (shorts). The indicator plots the suggested stop as a red dashed line. Max risk: 1-2% of account. Divergence setups typically offer tighter stops with better R:R.",
    targetStrategy: "For momentum trades: TP1 at 1:1.5 R:R, TP2 at 1:3 R:R. When the Surge Score is extremely high (>85), expect a strong move — extend TP3 to 1:5 R:R. For divergence trades: TP1 at the previous opposing swing point, TP2 at the next structural level. Close 50% at TP1, trail rest with the 9 EMA. Average expected R:R is 1:2.5 for momentum trades and 1:3.5 for divergence trades.",
    recommendedSettings: "FAST SCALPING (1-5 min): RSI Period: 7, MACD Fast/Slow/Signal: 8/17/9, Volume MA: 10, Surge Threshold: 65/35. Best for Nifty, Bank Nifty, BTC.\nSTANDARD (15 min - 1 hour): RSI Period: 14, MACD: 12/26/9, Volume MA: 20, Surge Threshold: 70/30. Default and recommended for all instruments.\nSWING (4 hour - Daily): RSI Period: 21, MACD: 19/39/9, Volume MA: 30, Surge Threshold: 75/25. Best for Forex, Gold, stocks.\nCRYPTO MODE: RSI Period: 10, MACD: 10/21/7, Volume MA: 15, Surge Threshold: 65/35. Optimized for 24/7 crypto markets with higher volatility.",
  },
  {
    name: "Volatility Edge",
    slug: "volatility-edge",
    shortDescription: "Master volatility with Bollinger Band squeezes, ATR-based signals, and volatility regime classification.",
    description: "Volatility Edge gives you a complete understanding of market volatility and how to trade it profitably. The indicator classifies the current market into volatility regimes -- low, normal, high, and extreme -- and adjusts its signals accordingly.\nThe core engine uses a combination of Bollinger Band squeeze detection, ATR breakout signals, and Keltner Channel analysis to identify when volatility is about to expand or contract. This gives you a significant edge in timing your entries for maximum profit potential.\nThe indicator also includes a unique volatility mean-reversion system that identifies when price has stretched too far from its norm and is likely to snap back.",
    category: "Volatility",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Volatility regime classification system",
      "Bollinger Band squeeze detector",
      "ATR-based breakout signals",
      "Volatility mean-reversion alerts",
      "Keltner Channel integration",
      "Historical volatility comparison",
    ],
    winRate: "70.1%",
    avgReturn: "+2.3%",
    totalTrades: "1,103",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "GBP/JPY", "Gold (XAU/USD)", "Crude Oil", "VIX", "S&P 500"],
    bestTimeframes: ["15 min", "30 min", "1 hour", "4 hour", "Daily"],
    signalLogic: "Volatility Edge classifies the market into four regimes based on the Bollinger Band Width (BBW) percentile relative to the last 100 periods: LOW (0-25th percentile, blue background), NORMAL (25-50th, no background), HIGH (50-75th, light orange), EXTREME (75-100th, red). A 'squeeze' occurs when the Bollinger Bands contract inside the Keltner Channels — this signals an imminent volatility expansion.\nThe breakout signal fires when a squeeze releases (BBs expand back outside KCs) and price closes decisively above/below the upper/lower band. The mean-reversion signal fires when price reaches 2.5+ standard deviations from the mean in a HIGH or EXTREME regime, signaling an overextension likely to snap back.",
    entryConditions: "SQUEEZE BREAKOUT LONG: After a squeeze (BB inside KC for 6+ candles), enter when price closes above the upper Bollinger Band with the BBW expanding. The candle must close in the upper 25% of its range for confirmation.\nSQUEEZE BREAKOUT SHORT: After a squeeze, enter when price closes below the lower Bollinger Band with BBW expanding. Candle must close in the lower 25% of its range.\nMEAN REVERSION LONG: When price touches or exceeds -2.5 standard deviations (lower band extreme) in a HIGH/EXTREME regime, enter with a bullish reversal candle.\nMEAN REVERSION SHORT: When price touches or exceeds +2.5 standard deviations in HIGH/EXTREME regime.\nAVOID: Do not trade breakouts in EXTREME regime (already overextended). Do not trade mean-reversion in LOW regime (squeeze may continue).",
    exitConditions: "BREAKOUT EXIT: Exit when the BBW begins contracting (squeeze reforming) or when price crosses back inside the Bollinger Bands. Partial exit at 1:2 R:R, trail remainder with the middle Bollinger Band (20 SMA).\nMEAN REVERSION EXIT: Exit when price returns to the middle Bollinger Band (20 SMA). This is typically the primary target. Partial exit at 1 standard deviation from entry, full exit at the mean.\nREGIME CHANGE EXIT: If the regime shifts from HIGH to EXTREME during a mean-reversion trade, tighten stops immediately.",
    stopLossStrategy: "BREAKOUT trades: Stop at the opposite Bollinger Band at the time of entry, or 1x ATR from entry, whichever is tighter. MEAN REVERSION trades: Stop at 3 standard deviations from the mean (beyond the extreme band). This gives the trade room to work while capping risk. The indicator displays the exact stop level as a red zone. Max risk: 1.5% per trade.",
    targetStrategy: "BREAKOUT targets: TP1 at 1x the squeeze range (height of the BB squeeze), TP2 at 2x the squeeze range. The tighter the squeeze, the bigger the expansion — extended squeezes (10+ candles) often yield 3-5x moves. MEAN REVERSION targets: TP1 at 1 standard deviation toward the mean, TP2 at the 20 SMA (mean). Close 60% at TP1, 40% at TP2. Average R:R for squeeze breakouts is 1:3, for mean-reversion is 1:2.",
    recommendedSettings: "INTRADAY (15-30 min): BB Period: 20, BB StdDev: 2.0, KC Period: 20, KC Mult: 1.5, ATR: 14, Squeeze Min: 6 candles. Best for Nifty, Bank Nifty, indices.\nSWING (1-4 hour): BB Period: 20, BB StdDev: 2.0, KC Period: 20, KC Mult: 1.5, ATR: 14, Squeeze Min: 8 candles. Best for Forex, Gold, Crypto.\nDAILY: BB Period: 20, BB StdDev: 2.0, KC Period: 20, KC Mult: 2.0, ATR: 20, Squeeze Min: 10 candles. Best for stocks, ETFs, positional trading.\nHIGH VOLATILITY (Crypto/News): BB StdDev: 2.5, KC Mult: 2.0, Mean Reversion Threshold: 3.0 StdDev. For assets like BTC, ETH, or during event-driven volatility.",
  },
  {
    name: "Support & Resistance AI",
    slug: "support-resistance-ai",
    shortDescription: "AI-powered key level detection with strength scoring, zone clustering, and historical touch analysis.",
    description: "Support & Resistance AI uses machine learning algorithms to identify the most significant support and resistance levels on any chart. Unlike basic horizontal line tools, this indicator analyzes price action history, volume at price, and institutional footprint data to rank levels by their importance.\nEach level receives a strength score from 1-10 based on how many times price has reacted to it, the volume traded there, and how recently it was tested. The AI engine clusters nearby levels into zones, giving you a cleaner chart while maintaining accuracy.\nThe indicator also tracks level breaks and retests, automatically updating its analysis as market conditions evolve.",
    category: "Support/Resistance",
    tier: "premium",
    price: "9000",
    videoUrl: null,
    imageUrl: null,
    features: [
      "AI-powered level detection algorithm",
      "Strength scoring system (1-10 scale)",
      "Automatic zone clustering",
      "Break and retest tracking",
      "Historical touch count analysis",
      "Dynamic level updating",
    ],
    winRate: "69.4%",
    avgReturn: "+2.0%",
    totalTrades: "1,389",
    trialDays: 15,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "GBP/USD", "USD/JPY", "Gold (XAU/USD)", "S&P 500", "Apple (AAPL)"],
    bestTimeframes: ["5 min", "15 min", "1 hour", "4 hour", "Daily", "Weekly"],
    signalLogic: "The AI engine scans historical price data to find pivot points where price reversed or consolidated significantly. It assigns a strength score (1-10) based on: number of historical touches (30% weight), volume traded at the level (25% weight), recency of the last test (25% weight), and whether the level aligns with round numbers or Fibonacci levels (20% weight).\nLevels within 0.2% of each other are clustered into zones, displayed as shaded rectangles. The wider the zone, the more significant the level. Color coding: Green zones (support, strength 7+), red zones (resistance, strength 7+), gray zones (moderate, strength 4-6). Weak levels (1-3) are hidden by default.",
    entryConditions: "BOUNCE LONG: Price approaches a support zone (strength 7+) and forms a bullish rejection candle (hammer, engulfing, or pin bar). Enter when the candle closes back above the zone boundary. Confirmation: volume spike at the zone.\nBOUNCE SHORT: Price approaches a resistance zone (strength 7+) and forms a bearish rejection candle. Enter when the candle closes back below the zone boundary.\nBREAK & RETEST LONG: Price breaks above a resistance zone, then pulls back to retest it as new support. Enter when the retest candle closes bullish above the zone.\nBREAK & RETEST SHORT: Mirror of above. Price breaks below support, retests as resistance.\nSTRENGTH FILTER: Only trade levels with strength 7 or higher. Strength 9-10 levels offer the highest probability setups.",
    exitConditions: "EXIT LONG: At the next resistance zone (strength 6+) above entry. If the trade moves in your favor, trail stop below each successive support zone the price clears.\nEXIT SHORT: At the next support zone (strength 6+) below entry.\nINVALIDATION: If price closes beyond the entry zone in the opposite direction (e.g., closes below the support zone for a long trade), exit immediately — the level has failed.\nPARTIAL EXITS: Close 50% at the first intermediate level, trail rest to the next major zone.",
    stopLossStrategy: "For bounce trades: Place stop-loss 1-2 ticks beyond the opposite side of the zone. For example, if the support zone spans 18,000-18,020, stop goes at 17,995. For break & retest trades: Stop goes below the retested zone boundary. The indicator automatically suggests a stop level marked with a red dashed line. Zones with strength 9-10 typically have tighter stops because they hold more reliably.",
    targetStrategy: "Target the next zone of equal or greater strength in the direction of the trade. The indicator labels each zone with its strength score, so you can quickly identify the next target. TP1: Next zone (strength 5+). TP2: Next zone (strength 7+). For day traders: target zones within the same session's range. For swing traders: target zones from the higher timeframe. Average R:R: 1:2 for bounce trades, 1:3 for break & retest trades.",
    recommendedSettings: "SCALPING (1-5 min): Detection Period: 100 candles, Min Touches: 2, Cluster Width: 0.1%, Show Strength: 5+. Best for Nifty, Bank Nifty, BTC.\nINTRADAY (15 min - 1 hour): Detection Period: 300 candles, Min Touches: 3, Cluster Width: 0.2%, Show Strength: 6+. Default and recommended for all markets.\nSWING (4 hour - Daily): Detection Period: 500 candles, Min Touches: 3, Cluster Width: 0.3%, Show Strength: 7+. Best for Forex, Gold, indices.\nMULTI-TIMEFRAME: Enable HTF overlay to see Daily/Weekly levels on your intraday chart. These HTF levels act as the strongest S/R zones.",
  },
  {
    name: "Trend Pulse Lite",
    slug: "trend-pulse-lite",
    shortDescription: "Simple yet effective trend direction indicator with clear color-coded signals for any timeframe.",
    description: "Trend Pulse Lite is a free, beginner-friendly trend indicator that gives you a clear visual read on market direction. It uses a smoothed moving average algorithm to color-code your chart bars and plot directional arrows, making it instantly obvious whether the market is trending up, down, or ranging.\nPerfect for new traders who want a clean, no-nonsense view of the trend without information overload. Despite being free, Trend Pulse Lite uses a reliable methodology that more experienced traders also appreciate for quick chart scanning.\nUse it on any market and any timeframe to quickly assess trend direction before diving deeper with premium tools.",
    category: "Trend Following",
    tier: "free",
    price: "0",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Color-coded trend bars",
      "Directional arrow signals",
      "Works on all markets and timeframes",
      "Minimal chart clutter",
      "Beginner-friendly interface",
      "Customizable sensitivity settings",
    ],
    winRate: "61.3%",
    avgReturn: "+1.2%",
    totalTrades: "2,841",
    trialDays: null,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "EUR/USD", "Gold (XAU/USD)", "S&P 500"],
    bestTimeframes: ["5 min", "15 min", "1 hour", "Daily"],
    signalLogic: "Trend Pulse Lite uses a Smoothed Moving Average (SMMA) with a configurable period (default: 21) to determine trend direction. When price is above the SMMA and the SMMA is sloping upward, bars turn green (bullish). When price is below and SMMA slopes downward, bars turn red (bearish). Gray bars indicate a ranging/neutral market.\nUp arrows appear when bars transition from red/gray to green (trend shift bullish). Down arrows appear when bars transition from green/gray to red (trend shift bearish).",
    entryConditions: "LONG: Enter when a green up arrow appears and the current candle closes above the SMMA. Wait for the arrow candle to complete before entering.\nSHORT: Enter when a red down arrow appears and the current candle closes below the SMMA.\nFILTER: Avoid trading during gray (neutral) periods. The longer the gray period, the stronger the eventual breakout signal.",
    exitConditions: "EXIT LONG: When bars turn gray or red, or when a red down arrow appears.\nEXIT SHORT: When bars turn gray or green, or when a green up arrow appears.\nSimple and clean — follow the color of the bars for direction.",
    stopLossStrategy: "Place stop-loss at the SMMA line (the smoothed moving average value) at the time of entry. This provides a dynamic stop that respects the trend. For additional safety, add 0.5x ATR buffer beyond the SMMA. Beginners should risk no more than 1% per trade.",
    targetStrategy: "As a trend-following indicator, Trend Pulse Lite is best used with a trailing stop rather than fixed targets. Trail your stop with the SMMA — as long as bars remain green (longs) or red (shorts), stay in the trade. For fixed targets, aim for 1:2 R:R minimum.",
    recommendedSettings: "FAST (5 min): SMMA Period: 14. More signals but more noise.\nSTANDARD (15 min - 1 hour): SMMA Period: 21. Balanced signals and reliability.\nSLOW (4 hour - Daily): SMMA Period: 34. Fewer signals but higher quality.\nTIP: Pair Trend Pulse Lite with a premium indicator for confirmation. Use it as your trend direction filter.",
  },
  {
    name: "RSI Dashboard",
    slug: "rsi-dashboard",
    shortDescription: "Enhanced RSI indicator with multi-timeframe overview, divergence highlights, and overbought/oversold zones.",
    description: "RSI Dashboard takes the classic Relative Strength Index and transforms it into a powerful, multi-timeframe analysis tool -- completely free. It displays RSI values across multiple timeframes simultaneously, so you can spot confluence between short-term and long-term momentum.\nThe indicator automatically highlights bullish and bearish divergences between price and RSI, one of the most reliable reversal signals in technical analysis. Color-coded overbought and oversold zones make it easy to identify potential turning points at a glance.\nWhether you use RSI as your primary momentum tool or as a confirmation filter, this enhanced dashboard gives you everything you need without any cost.",
    category: "Momentum",
    tier: "free",
    price: "0",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Multi-timeframe RSI display",
      "Automatic divergence detection",
      "Color-coded overbought/oversold zones",
      "Customizable RSI periods",
      "Clean, non-overlapping panel",
      "Alert-ready for key RSI levels",
    ],
    winRate: "58.7%",
    avgReturn: "+0.9%",
    totalTrades: "3,456",
    trialDays: null,
    markets: ["Nifty 50", "Bank Nifty", "Bitcoin (BTC)", "Ethereum (ETH)", "EUR/USD", "Gold (XAU/USD)", "S&P 500"],
    bestTimeframes: ["5 min", "15 min", "1 hour", "4 hour", "Daily"],
    signalLogic: "RSI Dashboard displays the standard RSI oscillator (0-100) with enhanced visual zones: green background below 30 (oversold), red background above 70 (overbought), and a neutral 40-60 zone marked in gray. The dashboard panel shows RSI values from up to 5 timeframes simultaneously, allowing you to see momentum alignment.\nDivergence detection: The indicator identifies when price makes a new high/low but RSI does not confirm. Bullish divergence lines are drawn in green, bearish divergence lines in red. Only 'confirmed' divergences are shown (where the RSI swing point has been established).",
    entryConditions: "OVERSOLD BOUNCE: RSI crosses back above 30 from below, indicating the selling pressure is exhausting. Enter with a bullish candle confirmation.\nOVERBOUGHT SHORT: RSI crosses back below 70 from above. Enter with a bearish candle confirmation.\nDIVERGENCE LONG: Bullish divergence identified and RSI crosses above 40. Enter on the candle close.\nDIVERGENCE SHORT: Bearish divergence identified and RSI crosses below 60.\nCONFLUENCE: Highest probability when multiple timeframes show RSI in the same zone (e.g., all timeframes showing RSI < 35 = strong oversold confluence).",
    exitConditions: "EXIT LONG: When RSI reaches 65-70 (approaching overbought). For divergence trades, exit when RSI reaches the midline (50).\nEXIT SHORT: When RSI reaches 30-35 (approaching oversold).\nSIMPLE RULE: Exit when RSI enters the opposite zone from where you entered.",
    stopLossStrategy: "Place stop-loss below the most recent swing low (for longs) or above the most recent swing high (for shorts) that corresponds to the RSI extreme. Typically this is the candle where RSI was at its lowest/highest point. For divergence trades, stop goes below the second divergence low.",
    targetStrategy: "Target the RSI midline (50) for conservative trades. For aggressive targets, aim for the opposite extreme zone (70 for longs, 30 for shorts). Since RSI Dashboard is a free confirmation tool, it's best combined with a primary indicator for exact target levels. Average R:R: 1:1.5 to 1:2.",
    recommendedSettings: "STANDARD: RSI Period: 14, Overbought: 70, Oversold: 30. Works for all markets and timeframes.\nAGGRESSIVE: RSI Period: 7, Overbought: 80, Oversold: 20. Fewer but more extreme signals.\nCONSERVATIVE: RSI Period: 21, Overbought: 65, Oversold: 35. Smoother RSI with earlier zone entries.\nDASHBOARD TIMEFRAMES: Set to show 5m, 15m, 1H, 4H, Daily for intraday trading. Set to 1H, 4H, Daily, Weekly for swing trading.",
  },
];

export async function seedDatabase() {
  const existing = await db.select().from(indicators);
  if (existing.length > 0) return;

  for (const ind of seedIndicators) {
    await db.insert(indicators).values(ind);
  }
  console.log("Database seeded with indicators");
}
